package tunnel_server

import (
	"redock/platform/memory"
	"time"
)

const (
	// TableTunnelAgents stores remote clients ("agents") that registered with this server.
	TableTunnelAgents = "tunnel_agents"
	// TableTunnelAgentAssignments stores the tunnel definitions an admin assigns to an agent.
	TableTunnelAgentAssignments = "tunnel_agent_assignments"
)

// TunnelAgent is a remote redock client that self-registered with this tunnel
// server via the public endpoint. There is no login/key: the client is
// identified by a stable ClientID and described by its OS Hostname + OSUser so
// the admin can tell agents apart and treat them like users.
type TunnelAgent struct {
	memory.BaseEntity
	ClientID   string    `json:"client_id"`   // stable id generated by the client instance
	Hostname   string    `json:"hostname"`    // reported OS hostname
	OSUser     string    `json:"os_user"`     // reported OS username
	Version    string    `json:"version"`     // client version
	LastSeenAt time.Time `json:"last_seen_at"`
}

// TunnelAgentAssignment is a tunnel definition the admin assigns to an agent.
// The local target (ip:port the client forwards to) is set here on the server.
type TunnelAgentAssignment struct {
	memory.BaseEntity
	AgentID                  uint   `json:"agent_id"`
	Domain                   string `json:"domain"`            // full domain to bind on this server
	LocalHttpIp              string `json:"local_http_ip"`
	LocalHttpPort            int    `json:"local_http_port"`
	LocalTcpIp               string `json:"local_tcp_ip"`
	LocalTcpPort             int    `json:"local_tcp_port"`
	LocalUdpIp               string `json:"local_udp_ip"`
	LocalUdpPort             int    `json:"local_udp_port"`
	SourceBindIp             string `json:"source_bind_ip"`
	HostRewrite              string `json:"host_rewrite"`
	KeepaliveIntervalSeconds int    `json:"keepalive_interval_seconds"`
	AutoConnect              bool   `json:"auto_connect"` // client opens this tunnel automatically
	Enabled                  bool   `json:"enabled"`
}

// Label returns a human-friendly identifier for the agent (os_user@hostname).
func (a *TunnelAgent) Label() string {
	switch {
	case a.OSUser != "" && a.Hostname != "":
		return a.OSUser + "@" + a.Hostname
	case a.Hostname != "":
		return a.Hostname
	case a.OSUser != "":
		return a.OSUser
	default:
		return a.ClientID
	}
}

// --- Agent repo ---

func AllAgents() []*TunnelAgent {
	return memory.FindAll[*TunnelAgent](GetDB(), TableTunnelAgents)
}

// FindAgentByAssignedDomain returns the agent that has an assignment for the
// given full domain, or nil. Used to label agent-owned domains in the UI.
func FindAgentByAssignedDomain(fullDomain string) *TunnelAgent {
	if fullDomain == "" {
		return nil
	}
	for _, as := range memory.FindAll[*TunnelAgentAssignment](GetDB(), TableTunnelAgentAssignments) {
		if as.Domain == fullDomain {
			if a, err := FindAgentByID(as.AgentID); err == nil {
				return a
			}
			return nil
		}
	}
	return nil
}

func FindAgentByID(id uint) (*TunnelAgent, error) {
	return memory.FindByID[*TunnelAgent](GetDB(), TableTunnelAgents, id)
}

func FindAgentByClientID(clientID string) *TunnelAgent {
	if clientID == "" {
		return nil
	}
	for _, a := range AllAgents() {
		if a.ClientID == clientID {
			return a
		}
	}
	return nil
}

func DeleteAgentByID(id uint) error {
	for _, as := range AssignmentsByAgentID(id) {
		_ = memory.Delete[*TunnelAgentAssignment](GetDB(), TableTunnelAgentAssignments, as.ID)
	}
	return memory.Delete[*TunnelAgent](GetDB(), TableTunnelAgents, id)
}

// RegisterAgent upserts an agent by ClientID (keyless, public self-registration)
// and refreshes its descriptive fields and last-seen timestamp.
func RegisterAgent(clientID, hostname, osUser, version string) (*TunnelAgent, error) {
	now := time.Now()
	a := FindAgentByClientID(clientID)
	if a == nil {
		a = &TunnelAgent{
			ClientID:   clientID,
			Hostname:   hostname,
			OSUser:     osUser,
			Version:    version,
			LastSeenAt: now,
		}
		if err := memory.Create[*TunnelAgent](GetDB(), TableTunnelAgents, a); err != nil {
			return nil, err
		}
		return a, nil
	}
	if hostname != "" {
		a.Hostname = hostname
	}
	if osUser != "" {
		a.OSUser = osUser
	}
	if version != "" {
		a.Version = version
	}
	a.LastSeenAt = now
	if err := memory.Update[*TunnelAgent](GetDB(), TableTunnelAgents, a); err != nil {
		return nil, err
	}
	return a, nil
}

// TouchAgent updates the agent's last-seen timestamp.
func TouchAgent(a *TunnelAgent) {
	a.LastSeenAt = time.Now()
	_ = memory.Update[*TunnelAgent](GetDB(), TableTunnelAgents, a)
}

// --- Assignment repo ---

func AssignmentsByAgentID(agentID uint) []*TunnelAgentAssignment {
	out := make([]*TunnelAgentAssignment, 0)
	for _, as := range memory.FindAll[*TunnelAgentAssignment](GetDB(), TableTunnelAgentAssignments) {
		if as.AgentID == agentID {
			out = append(out, as)
		}
	}
	return out
}

func FindAssignmentByID(id uint) (*TunnelAgentAssignment, error) {
	return memory.FindByID[*TunnelAgentAssignment](GetDB(), TableTunnelAgentAssignments, id)
}

func CreateAssignment(a *TunnelAgentAssignment) error {
	return memory.Create[*TunnelAgentAssignment](GetDB(), TableTunnelAgentAssignments, a)
}

func UpdateAssignment(a *TunnelAgentAssignment) error {
	return memory.Update[*TunnelAgentAssignment](GetDB(), TableTunnelAgentAssignments, a)
}

func DeleteAssignmentByID(id uint) error {
	return memory.Delete[*TunnelAgentAssignment](GetDB(), TableTunnelAgentAssignments, id)
}
