package traffic_inspector

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"sync"
	"time"

	"redock/platform/memory"
)

const (
	caValidity   = 10 * 365 * 24 * time.Hour
	leafValidity = 90 * 24 * time.Hour
	rsaKeyBits   = 2048
)

// CAManager holds the root CA and issues per-hostname leaf certificates on
// demand, caching them so repeated connections to the same host don't pay
// the keygen/sign cost every time.
//
// Uses RSA (not ECDSA) for both the root and leaf certificates: some TLS
// clients (older/embedded stacks, certain CDN edge configurations) reject an
// ECDSA server certificate mid-handshake with a fatal "illegal_parameter"
// alert rather than a clean certificate-trust error — RSA is the more
// universally-compatible choice for a MITM proxy that wants to maximize how
// much real-world traffic it can successfully intercept.
type CAManager struct {
	rootCert *x509.Certificate
	rootKey  *rsa.PrivateKey
	certPEM  []byte

	mu    sync.Mutex
	cache map[string]*tls.Certificate
}

// LoadOrCreateCAManager loads the persisted root CA from the memory DB, or
// generates and persists a new one if none exists yet (mirrors the
// load-or-generate pattern used by platform/jwtsecrets for the JWT secret).
//
// If a persisted CA exists but fails to load (e.g. it was generated by an
// older redock build using a different key algorithm — this package
// switched from ECDSA to RSA leaf/root certs for broader TLS client
// compatibility), a fresh CA is generated and persisted in its place rather
// than treating that as a fatal error; the operator will need to reinstall
// the (new) CA on any already-configured inspected devices either way.
func LoadOrCreateCAManager(db *memory.Database) (*CAManager, error) {
	existing := memory.FindAll[*CAEntity](db, CATableName)
	if len(existing) > 0 {
		if manager, err := loadCAManager(existing[0]); err == nil {
			return manager, nil
		}
		return regenerateCAManager(db, existing[0])
	}

	return createCAManager(db)
}

func createCAManager(db *memory.Database) (*CAManager, error) {
	cert, key, certPEM, keyPEM, err := generateRootCA()
	if err != nil {
		return nil, fmt.Errorf("generate root CA: %w", err)
	}

	entity := &CAEntity{CertPEM: string(certPEM), KeyPEM: string(keyPEM)}
	if err := memory.Create[*CAEntity](db, CATableName, entity); err != nil {
		return nil, fmt.Errorf("persist root CA: %w", err)
	}

	return &CAManager{
		rootCert: cert,
		rootKey:  key,
		certPEM:  certPEM,
		cache:    make(map[string]*tls.Certificate),
	}, nil
}

// regenerateCAManager replaces an existing (unparseable) CA entity in place.
func regenerateCAManager(db *memory.Database, existing *CAEntity) (*CAManager, error) {
	cert, key, certPEM, keyPEM, err := generateRootCA()
	if err != nil {
		return nil, fmt.Errorf("generate root CA: %w", err)
	}

	existing.CertPEM = string(certPEM)
	existing.KeyPEM = string(keyPEM)
	if err := memory.Update[*CAEntity](db, CATableName, existing); err != nil {
		return nil, fmt.Errorf("persist regenerated root CA: %w", err)
	}

	return &CAManager{
		rootCert: cert,
		rootKey:  key,
		certPEM:  certPEM,
		cache:    make(map[string]*tls.Certificate),
	}, nil
}

func loadCAManager(entity *CAEntity) (*CAManager, error) {
	certBlock, _ := pem.Decode([]byte(entity.CertPEM))
	if certBlock == nil {
		return nil, fmt.Errorf("stored CA cert is not valid PEM")
	}
	cert, err := x509.ParseCertificate(certBlock.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse stored CA cert: %w", err)
	}

	keyBlock, _ := pem.Decode([]byte(entity.KeyPEM))
	if keyBlock == nil {
		return nil, fmt.Errorf("stored CA key is not valid PEM")
	}
	key, err := x509.ParsePKCS1PrivateKey(keyBlock.Bytes)
	if err != nil {
		return nil, fmt.Errorf("parse stored CA key: %w", err)
	}

	return &CAManager{
		rootCert: cert,
		rootKey:  key,
		certPEM:  []byte(entity.CertPEM),
		cache:    make(map[string]*tls.Certificate),
	}, nil
}

func generateRootCA() (*x509.Certificate, *rsa.PrivateKey, []byte, []byte, error) {
	key, err := rsa.GenerateKey(rand.Reader, rsaKeyBits)
	if err != nil {
		return nil, nil, nil, nil, err
	}

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, nil, nil, err
	}

	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			Organization: []string{"Redock DevStation"},
			CommonName:   "Redock Traffic Inspector Root CA",
		},
		NotBefore:             time.Now().Add(-time.Hour),
		NotAfter:              time.Now().Add(caValidity),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
	}

	derBytes, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return nil, nil, nil, nil, err
	}

	cert, err := x509.ParseCertificate(derBytes)
	if err != nil {
		return nil, nil, nil, nil, err
	}

	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: derBytes})

	keyDER := x509.MarshalPKCS1PrivateKey(key)
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: keyDER})

	return cert, key, certPEM, keyPEM, nil
}

// LeafCertificate returns a leaf certificate for the given hostname (SNI or
// IP literal), signed by the root CA, generating and caching it on first use.
func (m *CAManager) LeafCertificate(hostname string) (*tls.Certificate, error) {
	if hostname == "" {
		hostname = "redock-inspected-host"
	}

	m.mu.Lock()
	if cert, ok := m.cache[hostname]; ok {
		m.mu.Unlock()
		return cert, nil
	}
	m.mu.Unlock()

	cert, err := m.issueLeaf(hostname)
	if err != nil {
		return nil, err
	}

	m.mu.Lock()
	m.cache[hostname] = cert
	m.mu.Unlock()

	return cert, nil
}

func (m *CAManager) issueLeaf(hostname string) (*tls.Certificate, error) {
	key, err := rsa.GenerateKey(rand.Reader, rsaKeyBits)
	if err != nil {
		return nil, err
	}

	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, err
	}

	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: hostname},
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     time.Now().Add(leafValidity),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage:  []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}

	if ip := net.ParseIP(hostname); ip != nil {
		tmpl.IPAddresses = []net.IP{ip}
	} else {
		tmpl.DNSNames = []string{hostname}
	}

	derBytes, err := x509.CreateCertificate(rand.Reader, tmpl, m.rootCert, &key.PublicKey, m.rootKey)
	if err != nil {
		return nil, err
	}

	return &tls.Certificate{
		Certificate: [][]byte{derBytes, m.rootCert.Raw},
		PrivateKey:  key,
	}, nil
}

// GetCertificateFunc adapts LeafCertificate to the tls.Config.GetCertificate
// callback shape, keyed by the incoming ClientHello's SNI.
func (m *CAManager) GetCertificateFunc() func(*tls.ClientHelloInfo) (*tls.Certificate, error) {
	return func(hello *tls.ClientHelloInfo) (*tls.Certificate, error) {
		return m.LeafCertificate(hello.ServerName)
	}
}

// CACertPEM returns the root CA certificate in PEM form, for the client to
// install as a trusted root (GET /v1/vpn/ca.pem).
func (m *CAManager) CACertPEM() []byte {
	return m.certPEM
}
